#ifndef PARSERLIB__EXAMPLES__CALCULATOR__CALCULATOR_GRAMMAR__HPP
#define PARSERLIB__EXAMPLES__CALCULATOR__CALCULATOR_GRAMMAR__HPP


#include "parserlib.hpp"


extern parserlib::rule<> calculator_expr;


#endif //PARSERLIB__EXAMPLES__CALCULATOR__CALCULATOR_GRAMMAR__HPP
