p1 = 'aaaa';
p2 = "aaaa";
p3 = 'a';
p4 = 'a' .. 'z';
p5 = foo;
p6 = %bar%;
p7={p8};
p8=[p9];
p9=(p10);
p10=*p11;
p11=p12*;
p12=+p13;
p13=p14+;
p14=&p15;
p15=!p16;
p16=p17-p18;
p17=3..4*p19;
P19=3*P20;
p20=a b c, d, e;
p32=a | b | c;
%foo%='a' 'b';
a: b c;
a ::= b c | d
